### ISSUE TITLE
Refactor write-only code so I can sleep at night

### ISSUE THREAD

**Issue by christianbundy** [fraction/sshcd#14]
My face when I read [these three lines](https://github.com/fraction/sshcd/blob/17790a0920c376e670a3e5a2a907a886b6839893/sshcd#L2-L4):

![giphy](https://cloud.githubusercontent.com/assets/537700/7504873/541f4b46-f402-11e4-8b5d-ad76c876708a.gif)

Thanks @mcdonna for introducing me to the concept of [write-only code](http://en.wikipedia.org/wiki/Write-only_language).

**Comment by mcdonna** [comment]
LIKE!!

Cheers,
Donna
----
Donna McMaster
donna@donnamcmaster.com
(541) 738-2973 home/work/cell
http://www.donnamcmaster.com/
